=== albertocasadom/PFAT/reglas_peliculas.dtd
<!ELEMENT Peliculas (Pelicula+) >
<!ELEMENT Pelicula (caracteristicas_peli, titulo, director+, anio, genero+, actor+, nacionalidad+) >
<!ELEMENT genero (#PCDATA) >
<!ELEMENT actor (#PCDATA) >
<!ELEMENT director (#PCDATA) >
<!ELEMENT anio (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT nacionalidad (#PCDATA) >
<!ELEMENT caracteristicas_peli EMPTY>
<!ATTLIST caracteristicas_peli
	
	tiempo	CDATA #REQUIRED 
	unidades (H|MIN|SEG) "MIN" >

=== albertocasadom/PFAT/pelicula1.xml
<?xml version="1.0"?>

<!DOCTYPE Peliculas SYSTEM "reglas_peliculas.dtd">

<Peliculas>
	<Pelicula>
		<caracteristicas_peli tiempo="3" unidades="H" />
		<titulo>
			Star Wars
		</titulo>
		<director>
			George Lucas
		</director>
		<anio>
			1978
		</anio>
		<genero>
			Ciencia Ficcion
		</genero>
		<actor>
			Natali Portman
		</actor>
		<nacionalidad>
			Estadounidense
		</nacionalidad>
	</Pelicula>


	<Pelicula>
		<caracteristicas_peli tiempo="3" unidades="H" />
		<titulo>
			The Lord of the Rings
		</titulo>
		<director>
			Peter Robert Jackson
		</director>
		<anio>
			2003
		</anio>
		<genero>
			Novela
		</genero>
		<genero>
			Fantasia
		</genero>
		<actor>
			Vigo Mortensen
		</actor>
		<nacionalidad>
			Uruguayo
		</nacionalidad>
	</Pelicula>

</Peliculas>
